# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eo3LoZGd5CGCnuj40OlK-ltrZE3uT98L
"""

# ✅ Install necessary libraries
!pip install transformers gradio

# ✅ Import required libraries
import gradio as gr
from transformers import pipeline

# ✅ Initialize AI Chatbot (uses GPT-2 model)
chatbot = pipeline("text-generation", model="gpt2")

# ✅ Define function to generate chatbot responses
def chatbot_response(message):
    response = chatbot(message, max_length=100, do_sample=True)
    return response[0]["generated_text"]

# ✅ Create Gradio interface
demo = gr.Interface(
    fn=chatbot_response,
    inputs=gr.Textbox(lines=2, placeholder="Say something..."),
    outputs="text",
    title="AI Chatbot",
    description="Chat with an AI-powered assistant!"
)

# ✅ Launch the Gradio app
demo.launch()
