# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVlNJ8jhArxd46sjvkIpJ_fchMfGoqfM
"""

# ✅ Install necessary libraries
!pip install transformers gradio

# ✅ Import required libraries
import gradio as gr
from transformers import pipeline

# ✅ Initialize AI Text Generator (uses GPT-2 model)
text_generator = pipeline("text-generation", model="gpt2")

# ✅ Define function to generate language content
def generate_text(prompt):
    response = text_generator(prompt, max_length=100, do_sample=True)
    return response[0]["generated_text"]

# ✅ Create Gradio interface
demo = gr.Interface(
    fn=generate_text,
    inputs=gr.Textbox(lines=2, placeholder="Enter a prompt..."),
    outputs="text",
    title="AI Language Generator",
    description="Type a prompt and AI will generate text based on it."
)

# ✅ Launch the Gradio app
demo.launch()