# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hcZbmsSuOl4ZxLSabEq9H7w65JlDM1ED
"""

!pip install --upgrade nbfromat nbconvert

!pip install gradio

# Import necessary libraries
import gradio as gr
from transformers import pipeline

# Load pre-trained summarization model
summarizer = pipeline("summarization")

# Define function for summarization
def summarize_text(text):
    summary = summarizer(text, max_length=150, min_length=50, do_sample=False)
    return summary[0]['summary_text']

# Create Gradio interface
demo = gr.Interface(fn=summarize_text,
                    inputs=gr.Textbox(lines=10, placeholder="Enter text to summarize..."),
                    outputs="text",
                    title="AI Text Summarizer",
                    description="Enter a long text and get a concise summary using AI.")

# Launch the Gradio app
demo.launch()